#!/usr/bin/env python3
"""Figure documentation specs."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class FigureSpec:
    filename: str
    purpose: str
    data_source: str
    how_to_read: str
    focus: str
    conclusion_if_clear: str
    weak_trend_note: str
    coefficient_files: str
    recommend: str


def _spec(filename: str, purpose: str, data_source: str, how_to_read: str, focus: str, conclusion: str, coeffs: str, recommend: str) -> FigureSpec:
    return FigureSpec(
        filename=filename,
        purpose=purpose,
        data_source=data_source,
        how_to_read=how_to_read,
        focus=focus,
        conclusion_if_clear=conclusion,
        weak_trend_note="If the trend is weak, first check sample size, pending results, attack heterogeneity, and source_asr threshold sensitivity.",
        coefficient_files=coeffs,
        recommend=recommend,
    )


FIGURE_SPECS: Dict[str, FigureSpec] = {
    "rq1_dataset_facets_scatter_binned.png": _spec(
        "rq1_dataset_facets_scatter_binned.png",
        "Show the main transfer-stealth relation in the baseline strength results.",
        "master_results.csv, result_group=baseline_strength, complete rows only.",
        "X is transfer_rate, Y is stealthiness, facets are datasets, and the black line is a binned median trend.",
        "Whether binned stealthiness decreases as transfer_rate increases.",
        "Supports the main RQ1 claim that higher transferability tends to come with lower stealthiness.",
        "coefficients/rq1_by_dataset_correlations.csv",
        "yes",
    ),
    "rq1_result_group_spearman.png": _spec(
        "rq1_result_group_spearman.png",
        "Compare the transfer-stealth correlation strength across the five major result groups.",
        "master_results.csv, complete main-analysis rows grouped by result_group.",
        "Bars show Spearman(transfer_rate, stealthiness) for baseline_strength, cover_rate, label_mode, arch_acc, and noise_acc.",
        "Whether each experimental group preserves a negative transfer-stealth relationship, and which groups strengthen it.",
        "Supports the report structure that each major result group should first be interpreted through its own transfer-stealth correlation.",
        "coefficients/rq1_by_result_group_correlations.csv",
        "yes",
    ),
    "rq1_rank_binned_trend_by_dataset.png": _spec(
        "rq1_rank_binned_trend_by_dataset.png",
        "Check whether the RQ1 trend survives rank binning and is not only caused by extreme transfer_rate values.",
        "master_results.csv, complete baseline rows.",
        "X is transfer-rate rank bin, Y is median stealthiness.",
        "Whether rank-binned median stealthiness declines across bins.",
        "Supports robustness of the transfer-stealth tradeoff under rank-based visualization.",
        "coefficients/rq1_by_dataset_correlations.csv",
        "backup",
    ),
    "rq1_attack_dataset_spearman_heatmap.png": _spec(
        "rq1_attack_dataset_spearman_heatmap.png",
        "Show attack- and dataset-level heterogeneity in the transfer-stealth relation.",
        "master_results.csv, complete rows across available result groups.",
        "Color is Spearman(transfer_rate, stealthiness) for each attack-dataset cell.",
        "Which cells are strongly negative and which are weak or reversed.",
        "Supports the claim that the tradeoff is robust but heterogeneous.",
        "coefficients/rq1_by_dataset_attack_correlations.csv",
        "yes",
    ),
    "rq1_attack_metric_heatmap.png": _spec(
        "rq1_attack_metric_heatmap.png",
        "Compare attack families by median transfer_rate and median stealthiness.",
        "master_results.csv, complete rows.",
        "Rows are attacks and columns are normalized metric summaries.",
        "Whether high-transfer attacks tend to be low-stealth attacks.",
        "Shows attack type is a strong confounder in overall averages.",
        "tables/table_3_rq1_by_dataset_attack.csv",
        "backup",
    ),
    "rq1_defense_breakdown_by_attack.png": _spec(
        "rq1_defense_breakdown_by_attack.png",
        "Decompose stealthiness into the four source-domain defenses.",
        "master_results.csv, complete rows.",
        "Bars show mean stealth component for SentiNet, ScaleUp, STRIP, and IBD_PSC by attack.",
        "Whether stealth drops are broad across defenses or driven by one detector.",
        "Clarifies whether the stealthiness metric is stable across detectors.",
        "tables/table_10_defense_breakdown.csv",
        "backup",
    ),
    "rq1_source_asr_threshold_sensitivity.png": _spec(
        "rq1_source_asr_threshold_sensitivity.png",
        "Check whether the transfer-stealth relation is sensitive to the source_asr validity threshold.",
        "master_results.csv under source_asr>=0.05 and source_asr>=0.10 filters.",
        "Bars compare Spearman correlations under different source_asr thresholds.",
        "Whether the sign remains stable after increasing the threshold.",
        "Defends against the concern that rows with weak source-domain attacks drive the transfer-stealth trend.",
        "coefficients/rq1_source_asr_threshold_sensitivity.csv",
        "backup",
    ),
    "strength_metric_curves_by_attack.png": _spec(
        "strength_metric_curves_by_attack.png",
        "Use attack strength as a path variable to contextualize movement in the transfer-stealth plane.",
        "master_results.csv, result_group=baseline_strength.",
        "X is ordered strength level within each attack family because raw strength units differ across alpha/delta/s/eps; for BELT, alpha is the strength axis and mask_rate is treated as a fixed matching parameter.",
        "Whether strength paths explain movement toward higher transfer_rate and lower stealthiness.",
        "Shows strength is an observation window for the transfer-stealth relationship within attack families.",
        "coefficients/strength_tradeoff_slope_by_attack.csv",
        "backup",
    ),
    "strength_transfer_stealth_paths_by_attack.png": _spec(
        "strength_transfer_stealth_paths_by_attack.png",
        "Show the main strength-window evidence as attack-separated scatter regions in the transfer-stealth plane.",
        "master_results.csv, result_group=baseline_strength.",
        "Each subplot is one attack. Points are individual baseline-strength rows, colors indicate source dataset, and the two dashed parallel lines mark the central 10-90% residual band around the fitted transfer-stealth trend.",
        "Whether each attack occupies a high-transfer/low-stealth or low-transfer/high-stealth region.",
        "Supports within-attack evidence for RQ1 while keeping attack families separated.",
        "coefficients/strength_pairwise_delta.csv",
        "yes",
    ),
    "strength_pairwise_delta_heatmap.png": _spec(
        "strength_pairwise_delta_heatmap.png",
        "Summarize adjacent strength deltas by attack.",
        "coefficients/strength_pairwise_delta.csv.",
        "Color shows mean adjacent delta for transfer_rate and stealthiness.",
        "Whether delta_transfer_rate and delta_stealthiness tend to have opposite signs under adjacent strength movement.",
        "Controls configuration better than pooled averages when observing transfer-stealth movement.",
        "coefficients/strength_pairwise_delta.csv",
        "backup",
    ),
    "cover_rate_metric_curves.png": _spec(
        "cover_rate_metric_curves.png",
        "Show the cover-rate transfer-stealth scatter after removing WaNet.",
        "master_results.csv, result_group=cover_rate, attack_type != WaNet.",
        "X is target-domain ASR, Y is stealthiness. Points are individual rows, colors indicate attack type, marker styles indicate dataset, and the two dashed parallel lines mark each attack's central 10-90% residual band around the fitted transfer-stealth trend.",
        "Whether adaptive_blend and adaptive_patch occupy the expected transfer-stealth regions under the cover-rate window.",
        "Treats cover_rate as an internal observation window and removes WaNet because its cover-rate response is weak/noisy for this specific visual.",
        "coefficients/cover_rate_correlations.csv",
        "backup",
    ),
    "cover_rate_transfer_stealth_paths.png": _spec(
        "cover_rate_transfer_stealth_paths.png",
        "Show transfer-stealth movement paths as cover_rate changes.",
        "master_results.csv, result_group=cover_rate.",
        "Each path aggregates one attack over cover_rate.",
        "Whether increasing cover_rate moves points along the tradeoff plane.",
        "Shows how cover_rate is used to observe the transfer-stealth relationship.",
        "coefficients/cover_rate_pairwise_delta.csv",
        "backup",
    ),
    "cover_rate_pairwise_delta_heatmap.png": _spec(
        "cover_rate_pairwise_delta_heatmap.png",
        "Summarize adjacent cover_rate deltas by attack.",
        "coefficients/cover_rate_pairwise_delta.csv.",
        "Color shows mean adjacent delta for transfer_rate and stealthiness.",
        "Which attacks show the clearest paired transfer-stealth movement under cover-rate changes.",
        "Supports configuration-controlled observation of transfer-stealth movement under the cover-rate window.",
        "coefficients/cover_rate_pairwise_delta.csv",
        "yes",
    ),
    "label_mode_transfer_vs_stealth.png": _spec(
        "label_mode_transfer_vs_stealth.png",
        "Compare baseline-clean and all-to-one matched label-mode rows in the transfer-stealth plane.",
        "master_results.csv, matched rows from coefficients/label_mode_pairwise_delta.csv.",
        "Color is label_mode.",
        "Whether baseline clean SIG/UPGD and all-to-one SIG/UPGD points move to different regions of the transfer-stealth plane.",
        "Shows label mode as a matched window for observing transfer-stealth movement.",
        "coefficients/label_mode_pairwise_delta.csv",
        "backup",
    ),
    "label_mode_pairwise_delta.png": _spec(
        "label_mode_pairwise_delta.png",
        "Show all-to-one minus baseline-clean deltas where same-attack matched configurations exist.",
        "coefficients/label_mode_pairwise_delta.csv.",
        "Bars show delta_transfer_rate and delta_stealthiness by comparison.",
        "Whether SIG and UPGD all-to-one rows move toward higher transfer and lower stealth relative to baseline-clean counterparts.",
        "Supports matched observation of transfer-stealth movement without comparing against the whole baseline pool.",
        "coefficients/label_mode_pairwise_delta.csv",
        "backup",
    ),
    "label_mode_clean_to_dirty_arrows.png": _spec(
        "label_mode_clean_to_dirty_arrows.png",
        "Show the clean-label to dirty/all-to-one movement directly in the transfer-stealth plane.",
        "matched rows from master_results.csv using coefficients/label_mode_pairwise_delta.csv result directories.",
        "Open circles are matched clean-label baselines, filled circles are dirty/all-to-one rows, and arrows show the mean movement for each dataset-attack group.",
        "Whether clean-to-dirty movement points toward higher target-domain ASR and lower stealthiness.",
        "Gives the most intuitive visual explanation of the label-mode transfer-stealth movement.",
        "coefficients/label_mode_pairwise_delta.csv; tables/table_6_label_mode_summary.csv",
        "yes",
    ),
    "label_mode_clean_dirty_metric_summary.png": _spec(
        "label_mode_clean_dirty_metric_summary.png",
        "Compare matched clean-label and dirty/all-to-one metric means.",
        "matched rows from master_results.csv using coefficients/label_mode_pairwise_delta.csv result directories.",
        "Bars compare mean target-domain ASR and mean stealthiness for clean versus all-to-one within each dataset-attack group.",
        "Whether dirty/all-to-one raises target-domain ASR while reducing stealthiness under matched label-mode contrasts.",
        "Summarizes the two coordinates of the label-mode movement before looking at row-level deltas.",
        "tables/table_6_label_mode_summary.csv",
        "backup",
    ),
    "label_mode_delta_quadrant.png": _spec(
        "label_mode_delta_quadrant.png",
        "Show row-level clean-to-dirty matched deltas as transfer-stealth movement vectors.",
        "coefficients/label_mode_pairwise_delta.csv.",
        "X is delta target-domain ASR and Y is delta stealthiness for dirty/all-to-one minus clean; the lower-right quadrant means higher transfer and lower stealth.",
        "How many matched rows fall into the higher-transfer/lower-stealth quadrant.",
        "Provides row-level support for the clean-to-dirty movement rather than only group averages.",
        "coefficients/label_mode_pairwise_delta.csv",
        "yes",
    ),
    "label_mode_completeness.png": _spec(
        "label_mode_completeness.png",
        "Show which label-mode settings are complete or pending.",
        "tables/label_mode_completeness.csv.",
        "Bars show complete/partial/pending counts.",
        "Which label-mode results should not be over-interpreted.",
        "Prevents incomplete label-mode results from being treated as final evidence.",
        "tables/label_mode_completeness.csv",
        "conditional",
    ),
    "arch_metric_overview.png": _spec(
        "arch_metric_overview.png",
        "Compare metric levels across architectures.",
        "master_results.csv, result_group=baseline_strength and arch_acc.",
        "Grouped bars show clean_acc, transfer_rate, and stealthiness by dataset-architecture.",
        "Where SmallCNN, ResNet34, ResNet50, and DenseNet121 sit relative to baselines when matched rows are available.",
        "Provides context before pairwise architecture comparisons.",
        "tables/table_7_arch_summary.csv",
        "backup",
    ),
    "arch_pairwise_delta_summary.png": _spec(
        "arch_pairwise_delta_summary.png",
        "Main architecture/ACC paired-delta figure for intended contrasts.",
        "coefficients/arch_primary_pairwise_summary.csv.",
        "Bars show delta_clean_acc, delta_transfer_rate, and delta_stealthiness for SmallCNN minus ResNet18, ResNet34 minus ResNet18, ResNet50 minus ResNet18, and DenseNet121 minus ResNet18 when matched rows are available.",
        "Whether the intended architecture contrasts move points in the transfer-stealth plane, with ACC as context.",
        "Supports RQ2 by showing model capacity/ACC as a window that can move or reshape the tradeoff plane without merging unrelated baselines.",
        "coefficients/arch_primary_pairwise_summary.csv",
        "yes",
    ),
    "arch_tiny_archs_vs_resnet18.png": _spec(
        "arch_tiny_archs_vs_resnet18.png",
        "Compare the Tiny-ImageNet architecture supplements against the same original ResNet18 baseline.",
        "coefficients/arch_tiny_archs_vs_resnet18_summary.csv.",
        "Bars show matched deltas for ResNet34-ResNet18, ResNet50-ResNet18, and DenseNet121-ResNet18. Positive values mean the supplement architecture is higher than the matched ResNet18 row.",
        "Whether ResNet34, ResNet50, and DenseNet121 move target-domain ASR and stealthiness in similar or different directions under the same Tiny-ImageNet configuration grid.",
        "Keeps ResNet34, ResNet50, and DenseNet121 as separate matched contrasts rather than pooling all architecture rows.",
        "coefficients/arch_tiny_archs_vs_resnet18_summary.csv",
        "yes",
    ),
    "arch_relationship_shift_spearman.png": _spec(
        "arch_relationship_shift_spearman.png",
        "Show whether primary architecture contrasts alter the transfer-stealth correlation.",
        "coefficients/arch_primary_relationship_shift.csv.",
        "Bars show delta Spearman for each strict architecture contrast against the original ResNet18 baseline.",
        "Whether SmallCNN, ResNet34, ResNet50, or DenseNet121 strengthens or weakens the transfer-stealth relationship relative to the original ResNet18 baseline.",
        "Shows architecture as a window into relationship strength, not only metric means.",
        "coefficients/arch_primary_relationship_shift.csv",
        "yes",
    ),
    "arch_tiny_archs_relationship_shift.png": _spec(
        "arch_tiny_archs_relationship_shift.png",
        "Compare how ResNet34, ResNet50, and DenseNet121 change the Tiny-ImageNet transfer-stealth correlation relative to ResNet18.",
        "coefficients/arch_tiny_archs_vs_resnet18_relationship.csv.",
        "Bars show delta Spearman for each Tiny-ImageNet architecture contrast. Negative values mean the supplement architecture has a more negative transfer-stealth relationship than ResNet18.",
        "Whether ResNet50 or DenseNet121 behaves like ResNet34 or changes the transfer-stealth relationship in a different way.",
        "Supports the architecture analysis as relationship-first evidence, with ACC changes used as context.",
        "coefficients/arch_tiny_archs_vs_resnet18_relationship.csv",
        "yes",
    ),
    "arch_acc_vs_transfer_and_stealth.png": _spec(
        "arch_acc_vs_transfer_and_stealth.png",
        "Inspect direct ACC-to-single-metric relationships as auxiliary diagnostics.",
        "master_results.csv, architecture-related rows.",
        "Two panels show clean_acc vs transfer_rate and clean_acc vs stealthiness.",
        "Whether ACC directions are consistent.",
        "If inconsistent, ACC should remain a moderator/window for the transfer-stealth relationship, not a sole cause.",
        "coefficients/arch_acc_correlation_shift.csv",
        "backup",
    ),
    "arch_transfer_vs_stealth_by_arch.png": _spec(
        "arch_transfer_vs_stealth_by_arch.png",
        "Show architecture locations in the transfer-stealth plane.",
        "master_results.csv, architecture-related rows.",
        "Color is arch_base and facets are datasets.",
        "Whether weaker or stronger models occupy different regions.",
        "Helps interpret paired architecture deltas visually.",
        "coefficients/arch_pairwise_delta.csv",
        "backup",
    ),
    "arch_attack_heatmap.png": _spec(
        "arch_attack_heatmap.png",
        "Show architecture effects by attack.",
        "master_results.csv, architecture-related rows.",
        "Color summarizes median metrics by attack and architecture.",
        "Which attacks drive architecture effects.",
        "Prevents over-generalizing ACC conclusions across attacks.",
        "tables/table_7_arch_summary.csv",
        "backup",
    ),
    "arch_defense_breakdown.png": _spec(
        "arch_defense_breakdown.png",
        "Show detector-level stealth differences by architecture.",
        "master_results.csv, architecture-related rows.",
        "Grouped bars show stealth components across defenses.",
        "Which defenses drive architecture-level stealth changes.",
        "Explains detector response behind stealthiness changes.",
        "tables/table_10_defense_breakdown.csv",
        "backup",
    ),
    "noise_acc_vs_level_by_type.png": _spec(
        "noise_acc_vs_level_by_type.png",
        "Verify whether input noise creates a difficulty context for the transfer-stealth window.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "X is input_noise_level, Y is clean_acc, color is input_noise_type.",
        "Whether higher noise reduces clean_acc as context for later transfer-stealth movement.",
        "Validates noise as a difficulty window, not the main relationship by itself.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_metric_curves_by_noise_type.png": _spec(
        "noise_metric_curves_by_noise_type.png",
        "Show noise-level metric trends as auxiliary context for transfer-stealth movement.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "X is noise level, panels are metrics, color is noise type.",
        "Whether input difficulty helps explain transfer-stealth movement.",
        "Shows noise affects the setting in which the transfer-stealth relationship is observed.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_paired_delta_by_level.png": _spec(
        "noise_paired_delta_by_level.png",
        "Supplementary within-noise paired-delta figure.",
        "coefficients/noise_pairwise_delta.csv.",
        "Bars summarize adjacent noise-level deltas.",
        "Whether delta_transfer_rate and delta_stealthiness move together or apart as noise level changes, with ACC as context.",
        "Supports the within-noise observation window; the main RQ2 noise evidence is the noise-vs-baseline transfer-stealth movement.",
        "coefficients/noise_pairwise_delta.csv",
        "yes",
    ),
    "noise_transfer_vs_stealth_by_noise_type.png": _spec(
        "noise_transfer_vs_stealth_by_noise_type.png",
        "Compare noise types in the transfer-stealth plane.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "Color is noise type and point size can reflect noise level.",
        "Whether noise types occupy different regions.",
        "Shows different input perturbations can expose different transfer-stealth regions.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_transfer_vs_stealth_by_acc_bin.png": _spec(
        "noise_transfer_vs_stealth_by_acc_bin.png",
        "Show noise transfer-stealth relation by ACC bin.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "Facets or colors are ACC bins.",
        "Whether low/mid/high ACC bins have different slopes.",
        "Supports ACC-bin moderation of the transfer-stealth relationship within noise experiments.",
        "coefficients/noise_acc_bin_correlations.csv",
        "backup",
    ),
    "noise_clean_acc_metric_scatter.png": _spec(
        "noise_clean_acc_metric_scatter.png",
        "Directly inspect how clean ACC under noise relates to transferability and stealthiness.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "The two panels use clean ACC as X; Y is target-domain ASR in the first panel and stealthiness in the second. Colors indicate attack type and markers indicate noise type.",
        "Whether lower or higher clean ACC under noise corresponds to systematic changes in target-domain ASR and stealthiness.",
        "Shows ACC as a moderator/context variable for the noise experiment rather than only plotting noise level.",
        "coefficients/noise_by_type_level.csv; coefficients/noise_acc_bin_correlations.csv",
        "yes",
    ),
    "noise_vs_baseline_delta_acc_effect.png": _spec(
        "noise_vs_baseline_delta_acc_effect.png",
        "Show the matched noise-vs-baseline ACC delta effect on transferability and stealthiness.",
        "coefficients/noise_vs_baseline_rows.csv.",
        "X is delta clean ACC for noise minus ResNet18 baseline. The two panels show delta target-domain ASR and delta stealthiness. Zero lines separate increase/decrease regions.",
        "Whether ACC decrease under noise is accompanied by higher target-domain ASR and lower stealthiness relative to baseline.",
        "This is the clearest figure for discussing ACC/difficulty influence in the noise experiment.",
        "coefficients/noise_vs_baseline_overall.csv; coefficients/noise_vs_baseline_by_attack.csv; coefficients/noise_vs_baseline_rows.csv",
        "yes",
    ),
    "noise_acc_bin_metric_summary.png": _spec(
        "noise_acc_bin_metric_summary.png",
        "Summarize noise rows by clean-ACC bin.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "Bars show median clean ACC, target-domain ASR, and stealthiness within each ACC bin.",
        "Whether ACC bins occupy different transferability and stealthiness levels under noise.",
        "Provides a compact ACC-moderation view to support the scatter and delta figures.",
        "coefficients/noise_acc_bin_correlations.csv",
        "backup",
    ),
    "noise_attack_conditioned_acc_effect.png": _spec(
        "noise_attack_conditioned_acc_effect.png",
        "Show whether the ACC effect in the noise experiment is attack-dependent.",
        "coefficients/noise_attack_conditioned_acc_correlations.csv.",
        "Bars show Spearman(clean ACC, target-domain ASR) and Spearman(clean ACC, stealthiness) within each attack type.",
        "Whether clean ACC has the same relationship with transferability and stealthiness across attacks.",
        "Prevents the noise ACC analysis from being over-written as a single global monotonic rule.",
        "coefficients/noise_attack_conditioned_acc_correlations.csv",
        "backup",
    ),
    "noise_attack_heatmap.png": _spec(
        "noise_attack_heatmap.png",
        "Show attack-dependent noise effects.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "Heatmap summarizes median metrics by attack and noise type.",
        "Which attacks are most sensitive to noise.",
        "Prevents over-generalizing noise findings.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_defense_breakdown.png": _spec(
        "noise_defense_breakdown.png",
        "Show detector-level effects under noise.",
        "master_results.csv, result_group=noise_acc, strict baseline-matched rows only; unmatched old badnet/strength rows excluded.",
        "Bars show stealth components by defense and noise type.",
        "Which detectors drive noise stealth changes.",
        "Explains detector-level mechanism behind stealthiness changes.",
        "tables/table_10_defense_breakdown.csv",
        "backup",
    ),
    "rq2_acc_bin_spearman.png": _spec(
        "rq2_acc_bin_spearman.png",
        "Show whether ACC bins change transfer-stealth correlation strength.",
        "master_results.csv, complete rows.",
        "Bars show Spearman by acc_bin and result_group.",
        "Whether low/mid/high ACC bins have different signs or magnitudes.",
        "Supports ACC as a moderator.",
        "coefficients/rq2_acc_bin_correlations.csv",
        "backup",
    ),
    "rq2_intervention_delta_summary.png": _spec(
        "rq2_intervention_delta_summary.png",
        "Compare transfer-stealth movement across the three RQ2 ACC/difficulty/domain windows.",
        "coefficients/rq2_acc_intervention_comparison.csv.",
        "Bars show delta clean/target ACC, delta transfer_rate, and delta_stealthiness for architecture, noise-vs-baseline, and target-domain comparisons.",
        "Whether architecture, noise-vs-baseline, and target-domain windows move transfer_rate and stealthiness in the same direction.",
        "Shows ACC/difficulty/domain shift as moderators of transfer-stealth movement rather than one scalar cause.",
        "coefficients/rq2_acc_intervention_comparison.csv",
        "backup",
    ),
    "rq2_arch_vs_noise_comparison.png": _spec(
        "rq2_arch_vs_noise_comparison.png",
        "Compare architecture, noise-vs-baseline, and target-domain windows for RQ2.",
        "coefficients/rq2_acc_intervention_comparison.csv.",
        "Bars compare ACC, transfer, and stealth deltas across the three intervention sources.",
        "Whether the three ACC-related windows move the transfer-stealth relationship in the same way.",
        "Supports nuanced RQ2 interpretation by separating source-ACC, difficulty, and target-domain ACC windows.",
        "coefficients/rq2_acc_intervention_comparison.csv",
        "yes",
    ),
    "rq2_attack_conditioned_acc_effect.png": _spec(
        "rq2_attack_conditioned_acc_effect.png",
        "Control by attack when examining auxiliary ACC-to-single-metric effects.",
        "master_results.csv, complete rows.",
        "Bars show correlation between clean_acc and metrics within each attack.",
        "Whether ACC effects are attack-dependent.",
        "Shows ACC moderation of the transfer-stealth relationship depends on attack family.",
        "coefficients/rq2_attack_conditioned_acc_effect.csv",
        "backup",
    ),
    "target_domain_acc_transfer_overview.png": _spec(
        "target_domain_acc_transfer_overview.png",
        "Compare ImageNetV2-tiny and Qwen as a target-domain ACC window.",
        "master_results.csv, Tiny-ImageNet complete_analysis_row rows for ImageNetV2-tiny and Qwen.",
        "Bars compare mean target ACC, mean target-domain ASR, and source-domain stealthiness context between target domains.",
        "Whether the target domain with higher ACC also has higher target-domain ASR; stealthiness is source-defense context.",
        "Shows that target-domain ACC differences are a separate experimental factor from the default Tiny-ImageNet transfer setting.",
        "coefficients/target_domain_overall_summary.csv",
        "yes",
    ),
    "target_domain_paired_delta.png": _spec(
        "target_domain_paired_delta.png",
        "Show matched Qwen minus ImageNetV2 deltas for target ACC, target-domain ASR, and source-domain stealthiness context.",
        "coefficients/target_domain_paired_delta_overall.csv.",
        "Positive bars mean Qwen is higher than ImageNetV2; negative bars mean Qwen is lower; stealthiness deltas are expected to reflect source-domain defense context.",
        "Whether Qwen's higher target ACC corresponds to higher or lower target-domain ASR under matched source configurations.",
        "Supports the claim that target-domain ACC is a window on target ASR, not the same quantity as backdoor transferability.",
        "coefficients/target_domain_paired_delta_overall.csv",
        "yes",
    ),
    "target_domain_acc_vs_transfer.png": _spec(
        "target_domain_acc_vs_transfer.png",
        "Inspect target-domain ACC as an auxiliary window on target-domain ASR for ImageNetV2-tiny and Qwen.",
        "master_results.csv, Tiny-ImageNet complete_analysis_row rows for ImageNetV2-tiny and Qwen.",
        "X is target-domain clean ACC, Y is target-domain ASR, colors indicate the transfer dataset.",
        "Whether higher target ACC is associated with stronger or weaker target-domain ASR.",
        "Supports the target-domain ACC window analysis and should be read with paired deltas and regressions.",
        "coefficients/target_domain_acc_transfer_correlations.csv; coefficients/target_domain_acc_regressions.csv",
        "yes",
    ),
    "target_domain_transfer_stealth_by_domain.png": _spec(
        "target_domain_transfer_stealth_by_domain.png",
        "Compare ImageNetV2-tiny and Qwen in the transfer-stealth plane.",
        "master_results.csv, Tiny-ImageNet complete_analysis_row rows for ImageNetV2-tiny and Qwen.",
        "X is target-domain ASR, Y is detector-evasion stealthiness, colors indicate target domain.",
        "Whether the target-domain change shifts transferability while leaving source-domain stealthiness largely tied to the same model.",
        "Clarifies why Qwen is a target-domain ACC supplement and why stealthiness should be read as source-defense context.",
        "coefficients/target_domain_acc_bin_tradeoff_correlations.csv",
        "backup",
    ),
    "target_domain_attack_delta_heatmap.png": _spec(
        "target_domain_attack_delta_heatmap.png",
        "Show which attacks drive Qwen minus ImageNetV2 differences.",
        "coefficients/target_domain_paired_delta_summary.csv.",
        "Rows are attacks and columns are delta metrics; color shows the mean Qwen minus ImageNetV2 value.",
        "Which attacks lose or gain target-domain ASR when moving from ImageNetV2-tiny to Qwen.",
        "Shows target-domain movement is attack-dependent, with WaNet acting as an important boundary case.",
        "coefficients/target_domain_paired_delta_summary.csv",
        "backup",
    ),
}
