#!/usr/bin/env python3
"""Figure documentation specs."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class FigureSpec:
    filename: str
    purpose: str
    data_source: str
    how_to_read: str
    focus: str
    conclusion_if_clear: str
    weak_trend_note: str
    coefficient_files: str
    recommend: str


def _spec(filename: str, purpose: str, data_source: str, how_to_read: str, focus: str, conclusion: str, coeffs: str, recommend: str) -> FigureSpec:
    return FigureSpec(
        filename=filename,
        purpose=purpose,
        data_source=data_source,
        how_to_read=how_to_read,
        focus=focus,
        conclusion_if_clear=conclusion,
        weak_trend_note="If the trend is weak, first check sample size, pending results, attack heterogeneity, and source_asr threshold sensitivity.",
        coefficient_files=coeffs,
        recommend=recommend,
    )


FIGURE_SPECS: Dict[str, FigureSpec] = {
    "rq1_dataset_facets_scatter_binned.png": _spec(
        "rq1_dataset_facets_scatter_binned.png",
        "Show the main transfer-stealth relation in the baseline strength results.",
        "master_results.csv, result_group=baseline_strength, complete rows only.",
        "X is transfer_rate, Y is stealthiness, facets are datasets, and the black line is a binned median trend.",
        "Whether binned stealthiness decreases as transfer_rate increases.",
        "Supports the main RQ1 claim that higher transferability tends to come with lower stealthiness.",
        "coefficients/rq1_by_dataset_correlations.csv",
        "yes",
    ),
    "rq1_rank_binned_trend_by_dataset.png": _spec(
        "rq1_rank_binned_trend_by_dataset.png",
        "Check whether the RQ1 trend survives rank binning and is not only caused by extreme transfer_rate values.",
        "master_results.csv, complete baseline rows.",
        "X is transfer-rate rank bin, Y is median stealthiness.",
        "Whether rank-binned median stealthiness declines across bins.",
        "Supports robustness of the transfer-stealth tradeoff under rank-based visualization.",
        "coefficients/rq1_by_dataset_correlations.csv",
        "backup",
    ),
    "rq1_attack_dataset_spearman_heatmap.png": _spec(
        "rq1_attack_dataset_spearman_heatmap.png",
        "Show attack- and dataset-level heterogeneity in the transfer-stealth relation.",
        "master_results.csv, complete rows across available result groups.",
        "Color is Spearman(transfer_rate, stealthiness) for each attack-dataset cell.",
        "Which cells are strongly negative and which are weak or reversed.",
        "Supports the claim that the tradeoff is robust but heterogeneous.",
        "coefficients/rq1_by_dataset_attack_correlations.csv",
        "yes",
    ),
    "rq1_attack_metric_heatmap.png": _spec(
        "rq1_attack_metric_heatmap.png",
        "Compare attack families by median transfer_rate and median stealthiness.",
        "master_results.csv, complete rows.",
        "Rows are attacks and columns are normalized metric summaries.",
        "Whether high-transfer attacks tend to be low-stealth attacks.",
        "Shows attack type is a strong confounder in overall averages.",
        "tables/table_3_rq1_by_dataset_attack.csv",
        "backup",
    ),
    "rq1_defense_breakdown_by_attack.png": _spec(
        "rq1_defense_breakdown_by_attack.png",
        "Decompose stealthiness into the four source-domain defenses.",
        "master_results.csv, complete rows.",
        "Bars show mean stealth component for SentiNet, ScaleUp, STRIP, and IBD_PSC by attack.",
        "Whether stealth drops are broad across defenses or driven by one detector.",
        "Clarifies whether the stealthiness metric is stable across detectors.",
        "tables/table_10_defense_breakdown.csv",
        "backup",
    ),
    "rq1_source_asr_threshold_sensitivity.png": _spec(
        "rq1_source_asr_threshold_sensitivity.png",
        "Check source_asr denominator sensitivity for transfer_rate.",
        "master_results.csv under source_asr>=0.05 and source_asr>=0.10 filters.",
        "Bars compare Spearman correlations under different source_asr thresholds.",
        "Whether the sign remains stable after increasing the threshold.",
        "Defends against the concern that low source_asr inflated transfer_rate.",
        "coefficients/rq1_source_asr_threshold_sensitivity.csv",
        "backup",
    ),
    "strength_metric_curves_by_attack.png": _spec(
        "strength_metric_curves_by_attack.png",
        "Show how attack strength changes clean/source/transfer/stealth metrics.",
        "master_results.csv, result_group=baseline_strength.",
        "X is ordered strength level within each attack family because raw strength units differ across alpha/delta/s/eps/mask_rate.",
        "Whether stronger attacks raise transfer_rate and reduce stealthiness.",
        "Shows attack strength can move the tradeoff within attack families.",
        "coefficients/strength_tradeoff_slope_by_attack.csv",
        "backup",
    ),
    "strength_transfer_stealth_paths_by_attack.png": _spec(
        "strength_transfer_stealth_paths_by_attack.png",
        "Show transfer-stealth movement paths as attack strength changes.",
        "master_results.csv, result_group=baseline_strength.",
        "Each path aggregates one attack over increasing strength.",
        "Whether paths move toward higher transfer and lower stealth.",
        "Supports within-attack evidence for RQ1.",
        "coefficients/strength_pairwise_delta.csv",
        "yes",
    ),
    "strength_pairwise_delta_heatmap.png": _spec(
        "strength_pairwise_delta_heatmap.png",
        "Summarize adjacent strength deltas by attack.",
        "coefficients/strength_pairwise_delta.csv.",
        "Color shows mean adjacent delta for transfer_rate and stealthiness.",
        "Whether delta_transfer_rate and delta_stealthiness tend to have opposite signs.",
        "Controls configuration better than simple pooled averages.",
        "coefficients/strength_pairwise_delta.csv",
        "backup",
    ),
    "cover_rate_metric_curves.png": _spec(
        "cover_rate_metric_curves.png",
        "Show metric trends as cover_rate changes.",
        "master_results.csv, result_group=cover_rate.",
        "X is cover_rate; lines are median source_asr, transfer_rate, and stealthiness.",
        "Whether cover_rate changes attack behavior.",
        "Tests cover_rate as an internal mechanism variable.",
        "coefficients/cover_rate_correlations.csv",
        "backup",
    ),
    "cover_rate_transfer_stealth_paths.png": _spec(
        "cover_rate_transfer_stealth_paths.png",
        "Show transfer-stealth movement paths as cover_rate changes.",
        "master_results.csv, result_group=cover_rate.",
        "Each path aggregates one attack over cover_rate.",
        "Whether increasing cover_rate moves points in the tradeoff plane.",
        "Shows cover_rate can regulate transfer-stealth behavior.",
        "coefficients/cover_rate_pairwise_delta.csv",
        "backup",
    ),
    "cover_rate_pairwise_delta_heatmap.png": _spec(
        "cover_rate_pairwise_delta_heatmap.png",
        "Summarize adjacent cover_rate deltas by attack.",
        "coefficients/cover_rate_pairwise_delta.csv.",
        "Color shows mean adjacent delta for transfer_rate and stealthiness.",
        "Which attacks are most cover-rate sensitive.",
        "Supports a configuration-controlled cover-rate mechanism analysis.",
        "coefficients/cover_rate_pairwise_delta.csv",
        "yes",
    ),
    "label_mode_transfer_vs_stealth.png": _spec(
        "label_mode_transfer_vs_stealth.png",
        "Compare label modes in the transfer-stealth plane.",
        "master_results.csv, result_group=label_mode plus comparable baseline rows when available.",
        "Color is label_mode.",
        "Whether clean/default/all2one points separate.",
        "Shows whether label mechanism changes transfer and stealth.",
        "coefficients/label_mode_pairwise_delta.csv",
        "backup",
    ),
    "label_mode_pairwise_delta.png": _spec(
        "label_mode_pairwise_delta.png",
        "Show paired label-mode deltas where matched configurations exist.",
        "coefficients/label_mode_pairwise_delta.csv.",
        "Bars show delta_transfer_rate and delta_stealthiness by comparison.",
        "Whether label-mode changes move metrics systematically.",
        "Supports label-mode mechanism analysis only for complete comparisons.",
        "coefficients/label_mode_pairwise_delta.csv",
        "backup",
    ),
    "label_mode_completeness.png": _spec(
        "label_mode_completeness.png",
        "Show which label-mode settings are complete or pending.",
        "tables/label_mode_completeness.csv.",
        "Bars show complete/partial/pending counts.",
        "Which label-mode results should not be over-interpreted.",
        "Prevents incomplete label-mode results from being treated as final evidence.",
        "tables/label_mode_completeness.csv",
        "conditional",
    ),
    "arch_metric_overview.png": _spec(
        "arch_metric_overview.png",
        "Compare metric levels across architectures.",
        "master_results.csv, result_group=baseline_strength and arch_acc.",
        "Grouped bars show clean_acc, transfer_rate, and stealthiness by dataset-architecture.",
        "Where SmallCNN and ResNet34 sit relative to baselines.",
        "Provides context before pairwise architecture comparisons.",
        "tables/table_7_arch_summary.csv",
        "backup",
    ),
    "arch_pairwise_delta_summary.png": _spec(
        "arch_pairwise_delta_summary.png",
        "Main architecture/ACC paired-delta figure.",
        "coefficients/arch_pairwise_delta.csv.",
        "Bars show delta_clean_acc, delta_transfer_rate, and delta_stealthiness for matched architecture pairs.",
        "Whether model changes move ACC, transfer, and stealth together or apart.",
        "Supports RQ2 by showing model capacity/ACC can move the tradeoff plane.",
        "coefficients/arch_pairwise_delta.csv",
        "yes",
    ),
    "arch_relationship_shift_spearman.png": _spec(
        "arch_relationship_shift_spearman.png",
        "Show whether architecture changes alter the transfer-stealth correlation.",
        "coefficients/arch_relationship_shift.csv.",
        "Bars show delta Spearman for each new-architecture vs baseline comparison.",
        "Whether SmallCNN or ResNet34 strengthens or weakens the transfer-stealth relationship relative to matched baseline architectures.",
        "Shows architecture can change relationship strength, not only metric means.",
        "coefficients/arch_relationship_shift.csv",
        "yes",
    ),
    "arch_acc_vs_transfer_and_stealth.png": _spec(
        "arch_acc_vs_transfer_and_stealth.png",
        "Inspect direct ACC relationships with transfer and stealth.",
        "master_results.csv, architecture-related rows.",
        "Two panels show clean_acc vs transfer_rate and clean_acc vs stealthiness.",
        "Whether ACC directions are consistent.",
        "If inconsistent, ACC should be framed as a moderator, not a sole cause.",
        "coefficients/arch_acc_correlation_shift.csv",
        "backup",
    ),
    "arch_transfer_vs_stealth_by_arch.png": _spec(
        "arch_transfer_vs_stealth_by_arch.png",
        "Show architecture locations in the transfer-stealth plane.",
        "master_results.csv, architecture-related rows.",
        "Color is arch_base and facets are datasets.",
        "Whether weaker or stronger models occupy different regions.",
        "Helps interpret paired architecture deltas visually.",
        "coefficients/arch_pairwise_delta.csv",
        "backup",
    ),
    "arch_attack_heatmap.png": _spec(
        "arch_attack_heatmap.png",
        "Show architecture effects by attack.",
        "master_results.csv, architecture-related rows.",
        "Color summarizes median metrics by attack and architecture.",
        "Which attacks drive architecture effects.",
        "Prevents over-generalizing ACC conclusions across attacks.",
        "tables/table_7_arch_summary.csv",
        "backup",
    ),
    "arch_defense_breakdown.png": _spec(
        "arch_defense_breakdown.png",
        "Show detector-level stealth differences by architecture.",
        "master_results.csv, architecture-related rows.",
        "Grouped bars show stealth components across defenses.",
        "Which defenses drive architecture-level stealth changes.",
        "Explains detector response behind stealthiness changes.",
        "tables/table_10_defense_breakdown.csv",
        "backup",
    ),
    "noise_acc_vs_level_by_type.png": _spec(
        "noise_acc_vs_level_by_type.png",
        "Verify whether input noise changes clean ACC.",
        "master_results.csv, result_group=noise_acc.",
        "X is input_noise_level, Y is clean_acc, color is input_noise_type.",
        "Whether higher noise reduces clean_acc.",
        "Validates noise as a difficulty intervention.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_metric_curves_by_noise_type.png": _spec(
        "noise_metric_curves_by_noise_type.png",
        "Show noise-level trends for clean_acc, transfer_rate, and stealthiness.",
        "master_results.csv, result_group=noise_acc.",
        "X is noise level, panels are metrics, color is noise type.",
        "Whether input difficulty changes transfer and stealth.",
        "Shows noise affects more than clean accuracy.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_paired_delta_by_level.png": _spec(
        "noise_paired_delta_by_level.png",
        "Main noise paired-delta figure.",
        "coefficients/noise_pairwise_delta.csv.",
        "Bars summarize adjacent noise-level deltas.",
        "Whether delta_ACC, delta_transfer_rate, and delta_stealthiness move systematically.",
        "Supports RQ2 under an input-difficulty intervention.",
        "coefficients/noise_pairwise_delta.csv",
        "yes",
    ),
    "noise_transfer_vs_stealth_by_noise_type.png": _spec(
        "noise_transfer_vs_stealth_by_noise_type.png",
        "Compare noise types in the transfer-stealth plane.",
        "master_results.csv, result_group=noise_acc.",
        "Color is noise type and point size can reflect noise level.",
        "Whether noise types occupy different regions.",
        "Shows different input perturbations can affect the tradeoff differently.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_transfer_vs_stealth_by_acc_bin.png": _spec(
        "noise_transfer_vs_stealth_by_acc_bin.png",
        "Show noise transfer-stealth relation by ACC bin.",
        "master_results.csv, result_group=noise_acc.",
        "Facets or colors are ACC bins.",
        "Whether low/mid/high ACC bins have different slopes.",
        "Supports ACC moderation within noise experiments.",
        "coefficients/noise_acc_bin_correlations.csv",
        "backup",
    ),
    "noise_attack_heatmap.png": _spec(
        "noise_attack_heatmap.png",
        "Show attack-dependent noise effects.",
        "master_results.csv, result_group=noise_acc.",
        "Heatmap summarizes median metrics by attack and noise type.",
        "Which attacks are most sensitive to noise.",
        "Prevents over-generalizing noise findings.",
        "coefficients/noise_by_type_level.csv",
        "backup",
    ),
    "noise_defense_breakdown.png": _spec(
        "noise_defense_breakdown.png",
        "Show detector-level effects under noise.",
        "master_results.csv, result_group=noise_acc.",
        "Bars show stealth components by defense and noise type.",
        "Which detectors drive noise stealth changes.",
        "Explains detector-level mechanism behind stealthiness changes.",
        "tables/table_10_defense_breakdown.csv",
        "backup",
    ),
    "rq2_acc_bin_spearman.png": _spec(
        "rq2_acc_bin_spearman.png",
        "Show whether ACC bins change transfer-stealth correlation strength.",
        "master_results.csv, complete rows.",
        "Bars show Spearman by acc_bin and result_group.",
        "Whether low/mid/high ACC bins have different signs or magnitudes.",
        "Supports ACC as a moderator.",
        "coefficients/rq2_acc_bin_correlations.csv",
        "backup",
    ),
    "rq2_intervention_delta_summary.png": _spec(
        "rq2_intervention_delta_summary.png",
        "Compare deltas across architecture and noise interventions.",
        "coefficients/arch_pairwise_delta.csv and coefficients/noise_pairwise_delta.csv.",
        "Bars show delta_clean_acc, delta_transfer_rate, and delta_stealthiness by intervention source.",
        "Whether interventions move metrics in the same direction.",
        "Shows different routes to difficulty can have different effects.",
        "coefficients/rq2_arch_noise_comparison.csv",
        "backup",
    ),
    "rq2_arch_vs_noise_comparison.png": _spec(
        "rq2_arch_vs_noise_comparison.png",
        "Compare architecture and noise mechanisms for RQ2.",
        "architecture and noise coefficient summaries.",
        "Panels compare correlations and deltas across intervention sources.",
        "Whether architecture and noise tell the same ACC story.",
        "Supports wording ACC as a moderator rather than a single causal explanation.",
        "coefficients/rq2_arch_noise_comparison.csv",
        "yes",
    ),
    "rq2_attack_conditioned_acc_effect.png": _spec(
        "rq2_attack_conditioned_acc_effect.png",
        "Control by attack when examining ACC effects.",
        "master_results.csv, complete rows.",
        "Bars show correlation between clean_acc and metrics within each attack.",
        "Whether ACC effects are attack-dependent.",
        "Shows ACC moderation depends on attack family.",
        "coefficients/rq2_attack_conditioned_acc_effect.csv",
        "backup",
    ),
}
