#!/usr/bin/env python3
"""Summarize how CIFAR-10 input-noise difficulty changes transfer and stealth."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


def _corr(a: pd.Series, b: pd.Series) -> float:
    sub = pd.concat([a, b], axis=1).dropna()
    if len(sub) < 2:
        return float("nan")
    return float(sub.iloc[:, 0].corr(sub.iloc[:, 1]))


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze CIFAR-10 input-noise difficulty results.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).with_name("data_cifar10_small_cnn_no_nc.csv"),
        help="CSV generated by extract_all_results.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("noise_difficulty_summary_cifar10_small_cnn.csv"),
        help="Output summary CSV",
    )
    args = parser.parse_args()

    if not args.input.exists():
        raise FileNotFoundError(f"input CSV not found: {args.input}")

    df = pd.read_csv(args.input)
    if "input_noise_type" not in df.columns:
        df["input_noise_type"] = "none"
    if "input_noise_level" not in df.columns:
        df["input_noise_level"] = 0.0

    numeric_cols = [
        "input_noise_level",
        "clean_acc",
        "asr",
        "transfer_asr",
        "transfer_rate",
        "stealth_auc_avg",
        "stealth_tpr_avg",
    ]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    rows = []
    for (noise_type, noise_level), sub in df.groupby(["input_noise_type", "input_noise_level"], dropna=False):
        rows.append(
            {
                "input_noise_type": noise_type,
                "input_noise_level": noise_level,
                "n_points": int(len(sub)),
                "acc_mean": sub["clean_acc"].mean(),
                "asr_mean": sub["asr"].mean(),
                "transfer_asr_mean": sub["transfer_asr"].mean(),
                "transfer_rate_mean": sub["transfer_rate"].mean(),
                "stealth_auc_mean": sub["stealth_auc_avg"].mean(),
                "stealth_tpr_mean": sub["stealth_tpr_avg"].mean(),
                "corr_transfer_stealth_auc": _corr(sub["transfer_rate"], sub["stealth_auc_avg"]),
                "corr_transfer_stealth_tpr": _corr(sub["transfer_rate"], sub["stealth_tpr_avg"]),
                "corr_acc_transfer": _corr(sub["clean_acc"], sub["transfer_rate"]),
                "corr_acc_stealth_auc": _corr(sub["clean_acc"], sub["stealth_auc_avg"]),
                "corr_acc_stealth_tpr": _corr(sub["clean_acc"], sub["stealth_tpr_avg"]),
            }
        )

    out = pd.DataFrame(rows).sort_values(["input_noise_type", "input_noise_level"])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(args.output, index=False)
    print(f"saved {args.output} ({len(out)} rows)")
    if not out.empty:
        print(out.to_string(index=False))


if __name__ == "__main__":
    main()
